version: '3.9'

services:
  api:
    container_name: topicpad-api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./api/:/go/src
    tty: true
    depends_on:
      - mysql
    networks:
      - mysql-net
      - api-net

  mysql:
    image: mysql:8.0.28
    container_name: topicpad-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: topicpad_database
      MYSQL_USER: topicpad_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - mysql-net

volumes:
  db-data:
    driver: local

networks:
  mysql-net:  # APIサーバ<=>MySQL間用ネットワーク
  api-net: # クライアント<=>APIサーバ間用ネットワーク
